const appname = "MyBazar";
const appversion = "Version 1.0.0";
const credits = "@0xRahad";
const email = "Email";
const emailHint = "user@example.com";
const password = "Password";
const passwordHint = "********";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Mr. Person";
const forgotPass = "Forgot Password?";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termsAndCond = "Terms and Conditions";
const alreadyHaveAcc = "Already have an account? ";

const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";

const searchAnything = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    womenDress = "Women Dress",
    girlsWatches = " Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    featuredProduct = "Featured Products",
    tShirts = "TShirts",
    girlsDress = "Girls Dresses",
    topCategories = "Top Categories",
    featureCategories = "Feature Categories";
